matrix
  include:
    - language: go
    go: "1.9.2"
    before_install:
    - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
    - chmod +x $GOPATH/bin/dep
    - go get golang.org/x/mobile/cmd/gomobile
    - gomobile init
    install:
    - dep ensure -v
    - gomobile bind -target=android/arm
    - language: android
    android:
      components:
        - tools
        - platform-tools
        - build-tools-26.0.2
        - android-27
        - extra-android-m2repository
        - extra-google-m2repository
    before_install:
      - yes | sdkmanager "platforms;android-27"
